---
- hosts: all
  tasks:
    - name: upgrade all packages
      dnf:
        name: "*"
        state: latest

    - name: INSTALL TMUX
      dnf:
        name: tmux
        state: latest

    - name: Install EPEL release repository
      package:
        name: epel-release
        state: present

    - name: download remi repo
      get_url:
        url: "https://rpms.remirepo.net/enterprise/remi-release-9.3.rpm"
        dest: "/tmp/remi-release-9.3.rpm"
    
    - name: Import a key from a url
      ansible.builtin.rpm_key:
        state: present
        key: "https://rpms.remirepo.net/enterprise/9/RPM-GPG-KEY-remi"

    - name: install remi repo
      yum:
        name: /tmp/remi-release-9.3.rpm
        state: present

    - name: install php8.3
      package:
        name: "{{ item }}"
        state: present
      loop:
        - php
        - php-cli
        - php-gd
        - php-mbstring
        - php-opcache
        - php-mysql
        - php-redis
        - php-mysql
        - php-sqlite3
        - php-json
        - php-xml
        - php-pear
        - php-devel
        - php-pdo
        - php-common
        - php-zip
        - php-sodium
        - php-imagick
      notify:
        - Restart php-fpm
  handlers:
    - name: restart php-fpm
      systemd:
        name: php-fpm
        state: restarted
