---
- hosts: all
  tasks:
    - name: find all files that are older than 10 days
      find:
        paths: /data/log
        age: 10d
        recurse: yes
      register: filesOlderThan10
    - name: remove older than 10
      file:
        path: "{{ item.path }}" 
        state: absent
      with_items: "{{ filesOlderThan10.files }}"
    - name: find all proc ids
      find:
        paths: /proc/
        file_type: file
        recurse: no
        patterns: "^/d\/.*\/status"
        use_regex: True
      register: procidFiles
    - name: "showing results"
      debug:
        msg: "{{ procidFiles }}"
